[tool.poetry]
name = "mirscribe-vcf"
version = "0.1.0"
description = ".vcf file analysis pipeline"
authors = ["Nazif Tasbas <nazifts@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
numpy = "^1.26.4"
pyensembl = "^2.3.12"
xgboost = "^2.0.3"
psutil = "^5.9.8"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
snakeviz = "^2.2.0"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
